window.DIALOGUE_LINES = window.DIALOGUE_LINES || {};

DIALOGUE_LINES.prologue = [
  { name: "？？？", lines: [{segments: [{text: "あの...聞..........か...？"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "dialogue3Disappear"},{type: "textEnterChange", id: false},{type: "spriteChange", id: "none"},{type: "fade", color: "black", start: 1000, wait: 2000, finish: 500},{type: "bgmFadeOut", id: 1000}], autoNext: true, dialogueAutoNext: true, wait: 3500}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "background", id: "circleTrial", fade: 100},{type: "setting"},{type: "bgmChange", id: "prepare"},{type: "bgmPlay", id: 0.4}]}]},
  { name: "？？？", lines: [{segments: [{text: "あの...聞こ...ま...か...？"}]}]},
  { name: "？？？", lines: [{segments: [{text: "あの...聞こえてますか...？"}]}]},
  { name: "？？？", lines: [{segments: [{text: "良かった...聞こえるみたいですね。"}]}]},
  { name: "？？？", lines: [{segments: [{text: "何から説明すればいいのかわかりませんが..."}]}]},
  { name: "？？？", lines: [{segments: [{text: "えっとまずは自己紹介...て"}]},
                            {segments: [{text: "先に姿を見せないとだめですよね。"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "textEnterChange", id: false},{type: "dialogue3Disappear"},{type: "spriteChange", id: "TATURO/TATURO_normal"}], autoNext: true, dialogueAutoNext: true, wait: 2000}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "まずは、オーソドックスに自己紹介をしますね。"}], event: [{type: "textEnterChange", id: true},{type: "dialogue3Appear"},{type: "sePlay", id: "noticed"},{type: "flash", id: "white"}]},
                                        {segments: [{text: "私の名前は"},
                                                    {text: "ニシモト　タツロウ", class: "yellow"},
                                                    {text: "と申します。"}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "本当ならこの西大寺高校や他の先生方の事..."}]},
                                        {segments: [{text: "憎い"},
                                                    {text: "校長", class: "yellow"},
                                                    {text: "のことも説明しないとなんですが..."}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "時間もなさそうですね..."}]},
                                        {segments: [{text: "とりあえず今の状況を説明しますね。"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "dialogue3Disappear"},{type: "textEnterChange", id: false},{type: "background", id: "murderedYudai", fade: 1000},{type: "spriteChange", id: "none"},{type: "bgmPlay", id: 0.4},
    {type: "fade", color: "black", start: 1000, wait: 1000, finish: 1000}], autoNext: true, dialogueAutoNext: true, wait: 3500}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "退職させられたのは保健体育教員の"}], event: [{type: "dialogue3Appear"},{type: "textEnterChange", id: true}]},
                                        {segments: [{text: "オカモト　ユウダイ", class: "yellow"},
                                                    {text: "先生だった。"}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "退職理由は不明..."}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "なぜ彼は退職を選んだのか..."}]},
                                        {segments: [{text: "わかっていることと言えば..."}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "background", id: "gym", fade: 1000},{type: "dialogue3Disappear"},{type: "textEnterChange", id: false},{type: "fade", color: "black", start: 1000, wait: 1000, finish: 1000}], autoNext: true, dialogueAutoNext: true, wait: 3500}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "現場となった体育館は"},{text: "密室状態", class: "yellow"},{text: "であり、"}], event: [{type: "useDialog", id: "dialogueSpeaking"},{type: "speakingDialogueAppear"},{type: "textEnterChange", id: true}]},
                                        {segments: [{text: "しかも..."}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "speakingDialogueDisappear"},{type: "spriteChange", id: "RYUJI/Ryuji_Normal"},{type: "textEnterChange", id: false}], autoNext: true, dialogueAutoNext: true, wait: 2000}]},
  { name: "シノハラ　リュウジ", lines: [{segments: [{text: "さっき現場回りを調べてみたんやが、"}], event: [{type: "textEnterChange", id: true},{type: "speakingDialogueAppear"}]},
                                        {segments: [{text: "オカモト先生が書いたであろう"},{text: "退職届", class: "yellow"},{text: "が見つかったで。"}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "本当ですね...こんなのいつ書いたんでしょうか...？"}], event: [{type: "itemBoxShow"}]}]},
  { name: "シノハラ　リュウジ", lines: [{segments: [{text: "じゃが、１つ"},{text: "おかしな点", class: "yellow"},{text: "があってな..."}], event: [{type: "itemBoxOut"},{type: "spriteChange", id: "RYUJI/Ryuji_Think"}]}]},
  { name: "シノハラ　リュウジ", lines: [{segments: [{text: "俺はオカモト先生と同じ保健体育の先生やから"}], event: [{type: "spriteChange", id: "RYUJI/Ryuji_Normal"}]},
                                        {segments: [{text: "よくアイツの書いた字を見るんやが..."}]}]},
  { name: "シノハラ　リュウジ", lines: [{segments: [{text: "この退職届の筆跡とは"},{text: "明らかに違う", class: "yellow"},{text: "んや。"}], event: [{type: "flash", id: "white"},{type: "sePlay", id: "noticed"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "background", id: "none", fade: 1000},{type: "spriteChange", id: "none"},{type: "textEnterChange", id: false},{type: "speakingDialogueDisappear"}], autoNext: true, dialogueAutoNext: true, wait: 1500}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "ということらしい...他には..."}], event: [{type: "speakingDialogueAppear"},{type: "textEnterChange", id: true}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "textEnterChange", id: false},{type: "speakingDialogueDisappear"},{type: "background", id: "garden", fade: 1000},{type: "fade", color: "black", start: 1000, wait: 1000, finish: 1000}], autoNext: true, dialogueAutoNext: true, wait: 2000}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "spriteChange", id: "KENTO/Kento_Normal"}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: "ササノ　ケント", lines: [{segments: [{text: "さっきグラウンドの用具倉庫を見に行ったんですけど、"}], event: [{type: "textEnterChange", id: "true"},{type: "speakingDialogueAppear"},{type: "flash", id: "white"},{type: "sePlay", id: "noticed"}]},
                                    {segments: [{text: "中にあったはずのハンマーがなくなっていました。"}]}]},
  { name: "ササノ　ケント", lines: [{segments: [{text: "用具倉庫は鍵がかかっていたし、"}]},
                                    {segments: [{text: "しかも鍵はずっと職員室にあったはずなのに..."}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "textEnterChange", id: false},{type: "background", id: "none", fade: 1000},{type: "spriteChange", id: "none"},{type: "speakingDialogueDisappear"}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "わかっているのはそれだけです..."}], event: [{type: "textEnterChange", id: true},{type: "dialogue3Appear"},{type: "useDialog", id: "dialogue"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "bulletGet"},{type: "textEnterChange", id: false}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: " ", lines: [{segments: [{text: "オカモトの退職届", class: "yellow"},{text: "を手帳に記録しました。", class: "green"}],event: [{type: "textEnterChange", id: true}]},
                       {segments: [{text: "言弾（コトダマ）メニューから確認できます。", class: "green"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "bulletGet"},{type: "textEnterChange", id: false}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: " ", lines: [{segments: [{text: "シノハラの証言", class: "yellow"},{text: "を手帳に記録しました。", class: "green"}],event: [{type: "textEnterChange", id: true}]},
                       {segments: [{text: "言弾（コトダマ）メニューから確認できます。", class: "green"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "bulletGet"},{type: "textEnterChange", id: false}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: " ", lines: [{segments: [{text: "消えた体育倉庫のハンマー", class: "yellow"},{text: "を手帳に記録しました。", class: "green"}],event: [{type: "textEnterChange", id: true}]},
                       {segments: [{text: "言弾（コトダマ）メニューから確認できます。", class: "green"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "bulletGet"},{type: "textEnterChange", id: false}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: " ", lines: [{segments: [{text: "ササノの証言", class: "yellow"},{text: "を手帳に記録しました。", class: "green"}],event: [{type: "textEnterChange", id: true}]},
                       {segments: [{text: "言弾（コトダマ）メニューから確認できます。", class: "green"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "bulletGet"},{type: "textEnterChange", id: false}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: " ", lines: [{segments: [{text: "体育倉庫の鍵の所在", class: "yellow"},{text: "を手帳に記録しました。", class: "green"}],event: [{type: "textEnterChange", id: true}]},
                       {segments: [{text: "言弾（コトダマ）メニューから確認できます。", class: "green"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "bulletGet"},{type: "textEnterChange", id: false}], autoNext: true, dialogueAutoNext: true, wait: 1000}]},
  { name: " ", lines: [{segments: [{text: "密室の体育館", class: "yellow"},{text: "を手帳に記録しました。", class: "green"}],event: [{type: "textEnterChange", id: true}]},
                       {segments: [{text: "言弾（コトダマ）メニューから確認できます。", class: "green"}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "これらの情報...つまり"},{text: "言弾（コトダマ）", class: "yellow"},{text: "の詳細は、"}], event: [{type: "spriteChange", id: "TATURO/Taturo_Consider"}]},
                                        {segments: [{text: "後で確認してもらうとして..."}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "とにかく、この"},{text: "言弾（コトダマ）", class: "yellow"},{text: "を武器に、"}]},
                                        {segments: [{text: "私は真実に辿り着かなければなりません..."}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "正しい犯人を指摘出来れば、犯人だけが懲戒解雇..."}]},
                                        {segments: [{text: "間違えれば、犯人に百億円贈呈で犯人以外は全員懲戒解雇..."}]}]},
  { name: "ニシモト　タツロウ", lines: [{segments: [{text: "それが、これから始まる"},{text: "職員会議", class: "yellow"},{text: "のルールだからです。"}]}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "dialogue3Disappear"},{type: "textEnterChange", id: false},{type: "spriteChange", id: "none"},{type: "fade", color: "black", start: 1000, wait: 2000, finish: 500},{type: "bgmFadeOut", id: 1000}], autoNext: true, dialogueAutoNext: true, wait: 3500}]},
  { name: " ", lines: [{segments: [{text: " "}], event: [{type: "background", id: "circleTrial", fade: 100},{type: "setting"},{type: "bgmChange", id: "prepare"},{type: "bgmPlay", id: 0.4}]}]}
]
